version: "2"
linters:
  default: all
  disable:
    - depguard
    - dupl
    - dupword
    - err113
    - exhaustruct
    - funlen
    - gocognit
    - gocyclo
    - godot
    - godox
    - ireturn
    - lll
    - mnd
    - nestif
    - nlreturn
    - rowserrcheck
    - tagliatelle
    - testableexamples
    - testpackage
    - varnamelen
    - wastedassign
    - wrapcheck
    - wsl
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
