---
linters:
  enable-all: true
  disable:
    - rowserrcheck # WARN [linters_context] rowserrcheck is disabled because of generics. You can track the evolution of the generics support by following the https://github.com/golangci/golangci-lint/issues/2649. 
    - wastedassign # WARN [linters_context] wastedassign is disabled because of generics. You can track the evolution of the generics support by following the https://github.com/golangci/golangci-lint/issues/2649.
    - tagliatelle
    - wsl
    - err113
    - nlreturn
    - lll
    - godot
    - varnamelen
    - ireturn
    # TODO
    - dupl
    - wrapcheck
    - testpackage
    - godox
    - nestif
    - funlen
    - gocognit
    - gocyclo
    - exhaustruct
    - execinquery
    - dupword
    - testableexamples
    - depguard
    - gomnd # WARN The linter 'gomnd' is deprecated (since v1.58.0) due to: The linter has been renamed. Replaced by mnd. 
    # WARN [linters_context] copyloopvar: this linter is disabled because the Go version (1.20) of your project is lower than Go 1.22 
    # WARN [linters_context] intrange: this linter is disabled because the Go version (1.20) of your project is lower than Go 1.22
